// Seed data for the SAI Elite CRM demo.
// All dates are dynamically generated relative to "now" so the demo always
// feels current on the day the user opens the app.

import { Agent, AppNotification, Lead, Message, Property, Task } from './types';

const iso = (offsetDays: number, hour = 10, minute = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

export const seedAgents: Agent[] = [
  { id: 'agent-dhruv', name: 'Dhruv Khanna', initials: 'DK', role: 'agent', avatarTone: '#C5A059', responseAvgMinutes: 18, active: true },
  { id: 'agent-layla', name: 'Layla Al Marri', initials: 'LM', role: 'agent', avatarTone: '#0288D1', responseAvgMinutes: 12, active: true },
  { id: 'agent-omar', name: 'Omar Rashid', initials: 'OR', role: 'agent', avatarTone: '#7B4EDB', responseAvgMinutes: 24, active: true },
  { id: 'agent-priya', name: 'Priya Menon', initials: 'PM', role: 'agent', avatarTone: '#2E7D32', responseAvgMinutes: 15, active: true },
  { id: 'admin-rania', name: 'Rania Farouk', initials: 'RF', role: 'admin', avatarTone: '#8C6D33', responseAvgMinutes: 10, active: true },
];

export const seedLeads: Lead[] = [
  {
    id: 'lead-sarah',
    name: 'Sarah Khan',
    phone: '+971 50 234 8811',
    email: 'sarah.khan@example.com',
    source: 'Property Finder',
    stage: 'Negotiation',
    score: 87,
    scoreReasons: [
      'Viewed 3 properties in Marina',
      'Increased budget from 2.1M to 2.4M',
      'Asked about mortgage eligibility',
      'Responds within 5 minutes',
      'No viewing booked in past 3 days',
    ],
    budget: 2400000,
    bedrooms: '2 BR',
    area: 'Dubai Marina',
    intent: 'Buy',
    timeline: '1-2 months',
    lastContactAt: iso(-3, 14, 20),
    createdAt: iso(-14, 9, 15),
    assignedAgentId: 'agent-dhruv',
    notes: 'Prefers newer buildings, must have balcony. Mortgage pre-approval pending.',
    dealValue: 2320000,
    matchedPropertyIds: ['prop-marinavista', 'prop-livmarina'],
    callLogs: [
      { id: 'call-1', at: iso(-5, 11, 0), outcome: 'Interested', notes: 'Wants to see 2BR in Marina Gate + LIV.', agentId: 'agent-dhruv' },
      { id: 'call-2', at: iso(-3, 15, 30), outcome: 'Callback', notes: 'Follow-up on service charges question.', agentId: 'agent-dhruv' },
    ],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: true, mortgageDocs: false, mou: false },
    memory: {
      concerns: ['Service charges', 'Building age'],
      preferences: ['2BR+', 'Balcony', 'Newer building', 'Marina or JBR'],
    },
    concernFlag: 'Service charges',
  },
  {
    id: 'lead-ahmed',
    name: 'Ahmed Rahman',
    phone: '+971 55 907 1233',
    email: 'ahmed.rahman@example.com',
    source: 'Bayut',
    stage: 'Contacted',
    score: 72,
    scoreReasons: [
      'Investor profile — 5 year hold',
      'Asked for payment plan options',
      'Engaged with 2 off-plan brochures',
      'Not yet booked call',
    ],
    budget: 1800000,
    bedrooms: '1-2 BR',
    area: 'Dubai Hills / Downtown',
    intent: 'Invest',
    timeline: '3-6 months',
    lastContactAt: iso(-1, 12, 0),
    createdAt: iso(-9, 10, 30),
    assignedAgentId: 'agent-dhruv',
    notes: 'Overseas investor, wants long-term rental income. Prefers Sobha or Emaar.',
    dealValue: 1680000,
    matchedPropertyIds: ['prop-sobhah2'],
    callLogs: [{ id: 'call-3', at: iso(-1, 12, 0), outcome: 'Interested', notes: 'Requested Sobha Hartland II comparison deck.', agentId: 'agent-dhruv' }],
    checklist: { qualified: true, viewingBooked: false, offerSubmitted: false, mortgageDocs: false, mou: false },
    memory: { concerns: ['Completion delay risk'], preferences: ['20/40/40 plan', 'Rental yield 6%+'] },
  },
  {
    id: 'lead-james',
    name: 'James Wilson',
    phone: '+971 52 118 4400',
    email: 'james.wilson@example.com',
    source: 'Referral',
    stage: 'Negotiation',
    score: 78,
    scoreReasons: ['Offer submitted', 'Seller has not responded 18h', 'Financing already approved'],
    budget: 3100000,
    bedrooms: '3 BR',
    area: 'Palm Jumeirah',
    intent: 'Buy',
    timeline: 'Immediate',
    lastContactAt: iso(0, 9, 15),
    createdAt: iso(-25, 11, 0),
    assignedAgentId: 'agent-layla',
    notes: 'Second home buyer, ready to move. Seller follow-up needed before 4 PM.',
    dealValue: 3050000,
    matchedPropertyIds: ['prop-palm-villa'],
    callLogs: [],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: true, mortgageDocs: true, mou: false },
    memory: { concerns: ['Timing of transfer'], preferences: ['Sea view', 'Furnished'] },
  },
  {
    id: 'lead-fatima',
    name: 'Fatima Ali',
    phone: '+971 56 774 1102',
    email: 'fatima.ali@example.com',
    source: 'Instagram',
    stage: 'New',
    score: 55,
    scoreReasons: ['Enquired via Instagram DM', 'Budget indicated in first message', 'No response yet'],
    budget: 1200000,
    bedrooms: '1 BR',
    area: 'Business Bay',
    intent: 'Buy',
    timeline: '2-3 months',
    lastContactAt: iso(0, 8, 45),
    createdAt: iso(0, 8, 45),
    assignedAgentId: 'agent-omar',
    notes: 'First-time buyer.',
    dealValue: 0,
    matchedPropertyIds: [],
    callLogs: [],
    checklist: { qualified: false, viewingBooked: false, offerSubmitted: false, mortgageDocs: false, mou: false },
    memory: { concerns: [], preferences: ['Business Bay', 'Under 1.2M'] },
  },
  {
    id: 'lead-mohammed',
    name: 'Mohammed Al Suwaidi',
    phone: '+971 50 445 7710',
    email: 'mohammed.s@example.com',
    source: 'Website',
    stage: 'SiteVisit',
    score: 81,
    scoreReasons: ['Attended viewing', 'Requested floor plan', 'Referred by existing client'],
    budget: 5200000,
    bedrooms: '4 BR',
    area: 'Dubai Hills',
    intent: 'Buy',
    timeline: '1-2 months',
    lastContactAt: iso(-2, 16, 0),
    createdAt: iso(-11, 14, 0),
    assignedAgentId: 'agent-layla',
    notes: 'Family relocating from Abu Dhabi. Sensitive to school proximity.',
    dealValue: 5100000,
    matchedPropertyIds: [],
    callLogs: [],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: false, mortgageDocs: false, mou: false },
    memory: { concerns: ['School proximity'], preferences: ['Villa', 'Garden', 'Dubai Hills Estate'] },
  },
  {
    id: 'lead-elena',
    name: 'Elena Petrova',
    phone: '+971 54 220 9911',
    email: 'elena.p@example.com',
    source: 'WhatsApp',
    stage: 'ClosedWon',
    score: 100,
    scoreReasons: ['Deal completed', 'Introduced 2 referrals'],
    budget: 2800000,
    bedrooms: '3 BR',
    area: 'JBR',
    intent: 'Buy',
    timeline: 'Closed',
    lastContactAt: iso(-30, 10, 0),
    createdAt: iso(-90, 10, 0),
    assignedAgentId: 'agent-priya',
    notes: 'Delighted client. Send anniversary card in Q4.',
    dealValue: 2780000,
    matchedPropertyIds: [],
    callLogs: [],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: true, mortgageDocs: true, mou: true },
    memory: { concerns: [], preferences: ['JBR', 'High floor'] },
    closedAt: iso(-30, 10, 0),
    followUpDueAt: iso(-27, 10, 0),
    anniversaryAt: iso(335, 10, 0),
  },
  {
    id: 'lead-carlos',
    name: 'Carlos Mendes',
    phone: '+971 58 991 4467',
    email: 'carlos.mendes@example.com',
    source: 'Property Finder',
    stage: 'ClosedLost',
    score: 40,
    scoreReasons: ['Chose competitor', 'Budget mismatch', 'Slow response cycle'],
    budget: 1400000,
    bedrooms: '2 BR',
    area: 'JVC',
    intent: 'Buy',
    timeline: 'Closed',
    lastContactAt: iso(-15, 15, 0),
    createdAt: iso(-45, 15, 0),
    assignedAgentId: 'agent-omar',
    notes: 'Went with a competitor. Keep warm — may return in 12 months.',
    dealValue: 0,
    matchedPropertyIds: [],
    callLogs: [],
    checklist: {},
    memory: { concerns: ['Budget'], preferences: ['JVC'] },
    closedAt: iso(-15, 15, 0),
  },
];

export const seedProperties: Property[] = [
  {
    id: 'prop-marinavista',
    title: 'Marina Vista — 2503',
    area: 'Dubai Marina',
    address: 'Marina Vista Tower, Dubai Marina',
    price: 2320000,
    status: 'Under Offer',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1180,
    developer: 'Emaar',
    amenities: ['Balcony', 'Sea view', 'Pool', 'Gym', 'Concierge'],
    photoUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    ownerName: 'Karim Nasr',
    ownerPhone: '+971 50 118 0022',
    serviceCharges: 22,
    notes: 'Fresh handover, high floor.',
    createdAt: iso(-40),
  },
  {
    id: 'prop-livmarina',
    title: 'LIV Marina — 1802',
    area: 'Dubai Marina',
    address: 'LIV Residence, Dubai Marina',
    price: 2390000,
    status: 'Available',
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1126,
    developer: 'LIV Real Estate',
    amenities: ['Balcony', 'Sea view', 'Pool', 'Beach access'],
    photoUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    ownerName: 'Al Falak Holdings',
    ownerPhone: '+971 4 388 4400',
    serviceCharges: 24,
    notes: 'Motivated seller.',
    createdAt: iso(-30),
  },
  {
    id: 'prop-sobhah2',
    title: 'Sobha Hartland II — 2BR',
    area: 'Dubai Hills',
    address: 'Sobha Hartland II, MBR City',
    price: 1680000,
    status: 'Available',
    type: 'Off-Plan',
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1050,
    developer: 'Sobha Realty',
    amenities: ['Waterfront', 'Community park', 'School', 'Pool'],
    photoUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ownerName: 'Sobha Realty',
    ownerPhone: '+971 4 375 6666',
    serviceCharges: 18,
    notes: '20/40/40 payment plan. Handover Q4 2026.',
    createdAt: iso(-20),
  },
  {
    id: 'prop-palm-villa',
    title: 'Palm Jumeirah 3BR Signature Villa',
    area: 'Palm Jumeirah',
    address: 'Signature Villas, Palm Jumeirah',
    price: 3050000,
    status: 'Under Offer',
    type: 'Villa',
    bedrooms: 3,
    bathrooms: 4,
    sizeSqft: 4200,
    developer: 'Nakheel',
    amenities: ['Private beach', 'Pool', 'Furnished', 'Sea view'],
    photoUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
    ownerName: 'Ali Al Zaabi',
    ownerPhone: '+971 50 990 1122',
    serviceCharges: 28,
    notes: 'Off-market. Seller travelling this week.',
    createdAt: iso(-10),
  },
  {
    id: 'prop-downtown-penthouse',
    title: 'Downtown Boulevard Penthouse',
    area: 'Downtown Dubai',
    address: 'Boulevard Point, Downtown Dubai',
    price: 8900000,
    status: 'Available',
    type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 5,
    sizeSqft: 3600,
    developer: 'Emaar',
    amenities: ['Burj view', 'Private lift', 'Terrace', 'Concierge'],
    photoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ownerName: 'Meraas Holdings',
    ownerPhone: '+971 4 317 3999',
    serviceCharges: 35,
    notes: 'Prime Burj-facing unit.',
    createdAt: iso(-60),
  },
  {
    id: 'prop-jvc-townhouse',
    title: 'JVC Townhouse — 3BR',
    area: 'JVC',
    address: 'Nakheel Townhouses, JVC',
    price: 2100000,
    status: 'Available',
    type: 'Townhouse',
    bedrooms: 3,
    bathrooms: 4,
    sizeSqft: 2100,
    developer: 'Nakheel',
    amenities: ['Garden', 'Community pool', 'Kids play'],
    photoUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ownerName: 'Mira Investments',
    ownerPhone: '+971 4 552 9000',
    serviceCharges: 12,
    notes: 'Vacant on transfer.',
    createdAt: iso(-15),
  },
];

export const seedTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Follow up with Sarah Khan on service charges',
    type: 'Follow-up',
    priority: 'High',
    dueAt: iso(0, 14, 0),
    status: 'Pending',
    assignedAgentId: 'agent-dhruv',
    createdBy: 'admin-rania',
    leadId: 'lead-sarah',
    notes: 'Prep annual service-charge breakdown for Marina Vista.',
    createdAt: iso(-1, 9, 0),
  },
  {
    id: 'task-2',
    title: 'Send Ahmed Sobha Hartland II comparison deck',
    type: 'Document',
    priority: 'Medium',
    dueAt: iso(0, 17, 0),
    status: 'Pending',
    assignedAgentId: 'agent-dhruv',
    createdBy: 'agent-dhruv',
    leadId: 'lead-ahmed',
    notes: 'Include 20/40/40 vs 10/50/40 side-by-side.',
    createdAt: iso(-1, 12, 0),
  },
  {
    id: 'task-3',
    title: 'Chase seller response for James Wilson',
    type: 'Call',
    priority: 'Urgent',
    dueAt: iso(-1, 16, 0),
    status: 'Pending',
    assignedAgentId: 'agent-layla',
    createdBy: 'admin-rania',
    leadId: 'lead-james',
    notes: 'Seller silent 18h. Offer expiring.',
    createdAt: iso(-2, 10, 0),
  },
  {
    id: 'task-4',
    title: 'Property viewing — Mohammed at Dubai Hills',
    type: 'Viewing',
    priority: 'Medium',
    dueAt: iso(1, 10, 0),
    status: 'Pending',
    assignedAgentId: 'agent-layla',
    createdBy: 'agent-layla',
    leadId: 'lead-mohammed',
    notes: '4BR villa, family visit.',
    createdAt: iso(-1, 11, 0),
  },
  {
    id: 'task-5',
    title: 'Anniversary card — Elena Petrova',
    type: 'Follow-up',
    priority: 'Low',
    dueAt: iso(2, 9, 0),
    status: 'Pending',
    assignedAgentId: 'agent-priya',
    createdBy: 'agent-priya',
    leadId: 'lead-elena',
    notes: 'Post-close relationship touchpoint.',
    createdAt: iso(-1, 15, 0),
  },
  {
    id: 'task-6',
    title: 'Confirm Marina Vista handover checklist',
    type: 'Document',
    priority: 'Medium',
    dueAt: iso(-2, 12, 0),
    status: 'Completed',
    assignedAgentId: 'agent-dhruv',
    createdBy: 'admin-rania',
    propertyId: 'prop-marinavista',
    notes: 'Signed off.',
    createdAt: iso(-5, 10, 0),
    completedAt: iso(-2, 12, 30),
  },
];

export const seedMessages: Message[] = [
  {
    id: 'msg-1',
    channel: 'WhatsApp',
    from: 'Sarah Khan',
    fromContact: '+971 50 234 8811',
    preview: 'I like Marina Gate but I am worried about service charges…',
    fullText: 'Hi Dhruv, I like Marina Gate but I am worried about service charges. Can you send me the annual figure? Also, do you have a 2BR with balcony in a newer building?',
    receivedAt: iso(0, 8, 55),
    isRead: false,
    convertedToLeadId: 'lead-sarah',
  },
  {
    id: 'msg-2',
    channel: 'WhatsApp',
    from: 'Ahmed Rahman',
    fromContact: '+971 55 907 1233',
    preview: 'Do you have any off-plan options with a flexible plan?',
    fullText: 'Do you have any off-plan options with a flexible plan? I like 20/40/40 structure. Investment horizon is 5 years.',
    receivedAt: iso(0, 8, 40),
    isRead: false,
    convertedToLeadId: 'lead-ahmed',
  },
  {
    id: 'msg-3',
    channel: 'Instagram',
    from: 'Fatima Ali',
    fromContact: '@fatima.ae',
    preview: 'When is the next viewing for Business Bay?',
    fullText: 'Hi! I saw your Business Bay listing on IG. When is the next viewing? My budget is around 1.2M.',
    receivedAt: iso(0, 8, 30),
    isRead: false,
    convertedToLeadId: 'lead-fatima',
  },
  {
    id: 'msg-4',
    channel: 'Facebook',
    from: 'Zainab Hussain',
    fromContact: 'zainab.h.fb',
    preview: 'Looking for a 3BR in JBR — budget 3M.',
    fullText: 'Hi, looking for a 3BR in JBR — budget 3M. Ready to see this weekend. Please share options.',
    receivedAt: iso(0, 7, 50),
    isRead: false,
  },
  {
    id: 'msg-5',
    channel: 'WhatsApp',
    from: 'James Wilson',
    fromContact: '+971 52 118 4400',
    preview: 'Please share the transfer documents.',
    fullText: 'Please share the transfer documents when the seller confirms. Ready to move fast.',
    receivedAt: iso(-1, 16, 15),
    isRead: true,
    convertedToLeadId: 'lead-james',
  },
  {
    id: 'msg-6',
    channel: 'Instagram',
    from: 'Rakesh Verma',
    fromContact: '@rakesh.verma',
    preview: 'Investor here — off-plan in Downtown?',
    fullText: 'Investor here — looking for off-plan in Downtown. Budget 2.5M. Please DM.',
    receivedAt: iso(-1, 14, 0),
    isRead: false,
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'High-intent lead activity',
    body: 'Sarah Khan viewed Marina Vista twice — score jumped to 87.',
    kind: 'lead',
    createdAt: iso(0, 8, 0),
    read: false,
    leadId: 'lead-sarah',
  },
  {
    id: 'notif-2',
    title: 'Deal risk detected',
    body: 'Sarah Khan — mortgage approval document missing on Marina Gate deal.',
    kind: 'risk',
    createdAt: iso(0, 7, 30),
    read: false,
    leadId: 'lead-sarah',
  },
  {
    id: 'notif-3',
    title: 'Task overdue',
    body: 'Chase seller response for James Wilson — was due yesterday.',
    kind: 'reminder',
    createdAt: iso(-1, 17, 0),
    read: false,
    taskId: 'task-3',
  },
  {
    id: 'notif-4',
    title: 'New property match',
    body: 'Sobha Hartland II 2BR matches Ahmed Rahman at 92%.',
    kind: 'match',
    createdAt: iso(-1, 11, 30),
    read: true,
    leadId: 'lead-ahmed',
  },
];
