// Seed data for the SERRA Elite CRM demo — Ahmedabad market.

import { Agent, AppNotification, Lead, Message, Property, StickyNote, Task } from './types';

const iso = (offsetDays: number, hour = 10, minute = 0) => {
  const d = new Date();
  d.setDate(d.getDate() + offsetDays);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
};

export const seedAgents: Agent[] = [
  { id: 'agent-dhruv', name: 'Dhruv Khanna', initials: 'DK', role: 'agent', avatarTone: '#C5A880', responseAvgMinutes: 18, active: true },
  { id: 'agent-priya', name: 'Priya Mehta', initials: 'PM', role: 'agent', avatarTone: '#2563EB', responseAvgMinutes: 12, active: true },
  { id: 'agent-rohit', name: 'Rohit Shah', initials: 'RS', role: 'agent', avatarTone: '#7B4EDB', responseAvgMinutes: 24, active: true },
  { id: 'agent-ananya', name: 'Ananya Rao', initials: 'AR', role: 'agent', avatarTone: '#059669', responseAvgMinutes: 15, active: true },
  { id: 'admin-kavya', name: 'Kavya Desai', initials: 'KD', role: 'admin', avatarTone: '#8A6A39', responseAvgMinutes: 10, active: true },
];

export const seedLeads: Lead[] = [
  {
    id: 'lead-aarav',
    name: 'Aarav Patel',
    phone: '+91 98250 34411',
    email: 'aarav.patel@example.com',
    source: 'MagicBricks',
    stage: 'Negotiation',
    score: 87,
    scoreReasons: [
      'Viewed 3 properties in Prahlad Nagar',
      'Increased budget from ₹1.6 Cr to ₹1.85 Cr',
      'Asked about home loan eligibility',
      'Responds within 5 minutes',
      'No site visit booked in past 3 days',
    ],
    budget: 18500000,
    bedrooms: '3 BHK',
    area: 'Prahlad Nagar',
    intent: 'Buy',
    timeline: '1-2 months',
    lastContactAt: iso(-3, 14, 20),
    createdAt: iso(-14, 9, 15),
    assignedAgentId: 'agent-dhruv',
    notes: 'Prefers newer buildings, must have balcony + covered parking. Home loan pre-approval pending from HDFC.',
    dealValue: 18000000,
    matchedPropertyIds: ['prop-shivalik', 'prop-godrej'],
    callLogs: [
      { id: 'call-1', at: iso(-5, 11, 0), outcome: 'Interested', notes: 'Wants to see 3BHK in Shivalik & Godrej properties.', agentId: 'agent-dhruv', durationMinutes: 14 },
      { id: 'call-2', at: iso(-3, 15, 30), outcome: 'Callback', notes: 'Follow-up on maintenance charges question.', agentId: 'agent-dhruv', durationMinutes: 9 },
      { id: 'call-3', at: iso(-8, 10, 0), outcome: 'Interested', notes: 'Initial qualification call. Family of 4.', agentId: 'agent-dhruv', durationMinutes: 22 },
    ],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: true, mortgageDocs: false, mou: false },
    memory: {
      concerns: ['Maintenance charges', 'Society amenities'],
      preferences: ['3 BHK+', 'Balcony', 'Newer building', 'Prahlad Nagar / Bopal', 'Covered parking'],
    },
    concernFlag: 'Maintenance charges',
    talkTimeMinutes: 45,
  },
  {
    id: 'lead-ishaan',
    name: 'Ishaan Mehta',
    phone: '+91 99745 90712',
    email: 'ishaan.mehta@example.com',
    source: '99acres',
    stage: 'Contacted',
    score: 72,
    scoreReasons: [
      'Investor profile — 5 year hold',
      'Asked for payment plan options',
      'Engaged with 2 new-launch brochures',
      'Not yet booked site visit',
    ],
    budget: 14000000,
    bedrooms: '2-3 BHK',
    area: 'SG Highway / Shela',
    intent: 'Invest',
    timeline: '3-6 months',
    lastContactAt: iso(-1, 12, 0),
    createdAt: iso(-9, 10, 30),
    assignedAgentId: 'agent-dhruv',
    notes: 'NRI investor (Dubai), wants long-term rental income. Prefers Godrej or Adani.',
    dealValue: 13500000,
    matchedPropertyIds: ['prop-godrejnorth'],
    callLogs: [
      { id: 'call-4', at: iso(-1, 12, 0), outcome: 'Interested', notes: 'Requested Godrej North Star comparison deck.', agentId: 'agent-dhruv', durationMinutes: 11 },
    ],
    checklist: { qualified: true, viewingBooked: false, offerSubmitted: false, mortgageDocs: false, mou: false },
    memory: { concerns: ['Possession delay risk'], preferences: ['20/40/40 plan', 'Rental yield 5%+', 'RERA registered'] },
    talkTimeMinutes: 11,
  },
  {
    id: 'lead-vihaan',
    name: 'Vihaan Trivedi',
    phone: '+91 90992 11840',
    email: 'vihaan.t@example.com',
    source: 'Referral',
    stage: 'Negotiation',
    score: 78,
    scoreReasons: ['Offer submitted', 'Seller has not responded 18h', 'Financing already approved'],
    budget: 32000000,
    bedrooms: '4 BHK',
    area: 'Bodakdev',
    intent: 'Buy',
    timeline: 'Immediate',
    lastContactAt: iso(0, 9, 15),
    createdAt: iso(-25, 11, 0),
    assignedAgentId: 'agent-priya',
    notes: 'Second home buyer, ready to move. Seller follow-up needed before 4 PM.',
    dealValue: 31500000,
    matchedPropertyIds: ['prop-applewood'],
    callLogs: [
      { id: 'call-5', at: iso(-2, 13, 0), outcome: 'Interested', notes: 'Offer negotiated to ₹3.15 Cr.', agentId: 'agent-priya', durationMinutes: 26 },
    ],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: true, mortgageDocs: true, mou: false },
    memory: { concerns: ['Timing of registration'], preferences: ['Bodakdev', 'Furnished', 'Servant quarter'] },
    talkTimeMinutes: 26,
  },
  {
    id: 'lead-diya',
    name: 'Diya Desai',
    phone: '+91 96770 41102',
    email: 'diya.desai@example.com',
    source: 'Instagram',
    stage: 'New',
    score: 55,
    scoreReasons: ['Enquired via Instagram DM', 'Budget indicated in first message', 'No response yet'],
    budget: 6500000,
    bedrooms: '2 BHK',
    area: 'Vastrapur',
    intent: 'Buy',
    timeline: '2-3 months',
    lastContactAt: iso(0, 8, 45),
    createdAt: iso(0, 8, 45),
    assignedAgentId: 'agent-rohit',
    notes: 'First-time buyer.',
    dealValue: 0,
    matchedPropertyIds: [],
    callLogs: [],
    checklist: { qualified: false, viewingBooked: false, offerSubmitted: false, mortgageDocs: false, mou: false },
    memory: { concerns: [], preferences: ['Vastrapur / IIM area', 'Under ₹65L'] },
    talkTimeMinutes: 0,
  },
  {
    id: 'lead-kabir',
    name: 'Kabir Joshi',
    phone: '+91 98795 88710',
    email: 'kabir.joshi@example.com',
    source: 'Website',
    stage: 'SiteVisit',
    score: 81,
    scoreReasons: ['Attended site visit', 'Requested floor plan', 'Referred by existing client'],
    budget: 42000000,
    bedrooms: '4 BHK',
    area: 'Thaltej / Bodakdev',
    intent: 'Buy',
    timeline: '1-2 months',
    lastContactAt: iso(-2, 16, 0),
    createdAt: iso(-11, 14, 0),
    assignedAgentId: 'agent-priya',
    notes: 'Family relocating from Mumbai. Wants proximity to good schools (DPS / Anand Niketan).',
    dealValue: 41000000,
    matchedPropertyIds: [],
    callLogs: [
      { id: 'call-6', at: iso(-3, 11, 0), outcome: 'Interested', notes: 'Discussed penthouse options in Thaltej.', agentId: 'agent-priya', durationMinutes: 18 },
    ],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: false, mortgageDocs: false, mou: false },
    memory: { concerns: ['School proximity'], preferences: ['Bungalow / Villa', 'Garden', 'Thaltej / Bodakdev'] },
    talkTimeMinutes: 18,
  },
  {
    id: 'lead-ananya-c',
    name: 'Ananya Bhatt',
    phone: '+91 94270 22099',
    email: 'ananya.b@example.com',
    source: 'WhatsApp',
    stage: 'ClosedWon',
    score: 100,
    scoreReasons: ['Deal completed', 'Introduced 2 referrals'],
    budget: 22000000,
    bedrooms: '3 BHK',
    area: 'Satellite',
    intent: 'Buy',
    timeline: 'Closed',
    lastContactAt: iso(-30, 10, 0),
    createdAt: iso(-90, 10, 0),
    assignedAgentId: 'agent-ananya',
    notes: 'Delighted client. Send Diwali gift + anniversary card in Nov.',
    dealValue: 21800000,
    matchedPropertyIds: [],
    callLogs: [],
    checklist: { qualified: true, viewingBooked: true, offerSubmitted: true, mortgageDocs: true, mou: true },
    memory: { concerns: [], preferences: ['Satellite', 'High floor'] },
    closedAt: iso(-30, 10, 0),
    followUpDueAt: iso(-27, 10, 0),
    anniversaryAt: iso(335, 10, 0),
    talkTimeMinutes: 0,
  },
  {
    id: 'lead-rishika',
    name: 'Rishika Modi',
    phone: '+91 98259 14467',
    email: 'rishika.modi@example.com',
    source: 'MagicBricks',
    stage: 'ClosedLost',
    score: 40,
    scoreReasons: ['Chose competitor', 'Budget mismatch', 'Slow response cycle'],
    budget: 8500000,
    bedrooms: '2 BHK',
    area: 'Gota',
    intent: 'Buy',
    timeline: 'Closed',
    lastContactAt: iso(-15, 15, 0),
    createdAt: iso(-45, 15, 0),
    assignedAgentId: 'agent-rohit',
    notes: 'Went with a competitor. Keep warm — may return in 12 months.',
    dealValue: 0,
    matchedPropertyIds: [],
    callLogs: [],
    checklist: {},
    memory: { concerns: ['Budget'], preferences: ['Gota'] },
    closedAt: iso(-15, 15, 0),
    talkTimeMinutes: 0,
  },
];

export const seedProperties: Property[] = [
  {
    id: 'prop-shivalik',
    title: 'Shivalik Parkside — 3 BHK',
    area: 'Prahlad Nagar',
    address: 'Shivalik Parkside, Prahlad Nagar, Ahmedabad',
    price: 18500000,
    status: 'Under Offer',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    sizeSqft: 1980,
    developer: 'Shivalik Group',
    amenities: ['Balcony', 'Clubhouse', 'Pool', 'Gym', 'Kids play area', 'Covered parking'],
    photoUrl: 'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800',
    ownerName: 'Meera Kapadia',
    ownerPhone: '+91 98240 11002',
    serviceCharges: 4,
    notes: 'Fresh possession, 14th floor.',
    createdAt: iso(-40),
  },
  {
    id: 'prop-godrej',
    title: 'Godrej Garden City — 3 BHK',
    area: 'Jagatpur / SG Highway',
    address: 'Godrej Garden City, near SG Highway',
    price: 17900000,
    status: 'Available',
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 3,
    sizeSqft: 1850,
    developer: 'Godrej Properties',
    amenities: ['Balcony', 'Landscaped gardens', 'Pool', 'Clubhouse'],
    photoUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
    ownerName: 'Godrej Properties Ltd',
    ownerPhone: '+91 79 4030 4030',
    serviceCharges: 4,
    notes: 'RERA GJ/03/AHMB/2024. Motivated developer pricing.',
    createdAt: iso(-30),
  },
  {
    id: 'prop-godrejnorth',
    title: 'Godrej North Star — 2 BHK',
    area: 'Shela / SG Highway',
    address: 'Godrej North Star, near Shela',
    price: 13500000,
    status: 'Available',
    type: 'New Launch',
    bedrooms: 2,
    bathrooms: 2,
    sizeSqft: 1250,
    developer: 'Godrej Properties',
    amenities: ['River view', 'Community park', 'Pool', 'School nearby'],
    photoUrl: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ownerName: 'Godrej Properties',
    ownerPhone: '+91 79 4030 5050',
    serviceCharges: 3,
    notes: '20/40/40 payment plan. Possession Dec 2026.',
    createdAt: iso(-20),
  },
  {
    id: 'prop-applewood',
    title: 'Applewood Estate — 4 BHK Bungalow',
    area: 'Bodakdev',
    address: 'Applewood Estate, Shantigram',
    price: 31500000,
    status: 'Under Offer',
    type: 'Bungalow',
    bedrooms: 4,
    bathrooms: 5,
    sizeSqft: 4200,
    developer: 'Adani Realty',
    amenities: ['Private garden', 'Pool', 'Servant quarter', 'Furnished'],
    photoUrl: 'https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=800',
    ownerName: 'Sanjay Vyas',
    ownerPhone: '+91 98254 09011',
    serviceCharges: 6,
    notes: 'Off-market. Owner relocating to Bangalore.',
    createdAt: iso(-10),
  },
  {
    id: 'prop-thaltej-penthouse',
    title: 'Iscon Riverside Penthouse — 4 BHK',
    area: 'Thaltej',
    address: 'Iscon Riverside, Thaltej',
    price: 62000000,
    status: 'Available',
    type: 'Penthouse',
    bedrooms: 4,
    bathrooms: 5,
    sizeSqft: 3600,
    developer: 'Iscon Group',
    amenities: ['River view', 'Private terrace', 'Home theatre', 'Concierge'],
    photoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ownerName: 'Iscon Group',
    ownerPhone: '+91 79 2687 5000',
    serviceCharges: 8,
    notes: 'Sabarmati riverfront-facing penthouse.',
    createdAt: iso(-60),
  },
  {
    id: 'prop-gota-townhouse',
    title: 'Sun South Park — 3 BHK Row House',
    area: 'Gota',
    address: 'Sun South Park, Gota',
    price: 9500000,
    status: 'Available',
    type: 'Bungalow',
    bedrooms: 3,
    bathrooms: 4,
    sizeSqft: 2100,
    developer: 'Sun Builders',
    amenities: ['Garden', 'Community pool', 'Kids play', 'Gated society'],
    photoUrl: 'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800',
    ownerName: 'Sun Builders',
    ownerPhone: '+91 79 2685 4400',
    serviceCharges: 2,
    notes: 'Vacant on registration.',
    createdAt: iso(-15),
  },
];

export const seedTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Follow up with Aarav Patel on maintenance charges',
    type: 'Follow-up',
    priority: 'High',
    dueAt: iso(0, 14, 0),
    status: 'Pending',
    assignedAgentId: 'agent-dhruv',
    createdBy: 'admin-kavya',
    leadId: 'lead-aarav',
    notes: 'Prep annual maintenance breakdown for Shivalik Parkside.',
    createdAt: iso(-1, 9, 0),
  },
  {
    id: 'task-2',
    title: 'Send Ishaan Godrej North Star comparison deck',
    type: 'Document',
    priority: 'Medium',
    dueAt: iso(0, 17, 0),
    status: 'Pending',
    assignedAgentId: 'agent-dhruv',
    createdBy: 'agent-dhruv',
    leadId: 'lead-ishaan',
    notes: 'Include 20/40/40 vs 10/50/40 side-by-side + RERA docs.',
    createdAt: iso(-1, 12, 0),
  },
  {
    id: 'task-3',
    title: 'Chase seller response for Vihaan Trivedi',
    type: 'Call',
    priority: 'Urgent',
    dueAt: iso(-1, 16, 0),
    status: 'Pending',
    assignedAgentId: 'agent-priya',
    createdBy: 'admin-kavya',
    leadId: 'lead-vihaan',
    notes: 'Seller silent 18h. Offer expiring.',
    createdAt: iso(-2, 10, 0),
  },
  {
    id: 'task-4',
    title: 'Site visit — Kabir at Thaltej',
    type: 'Site Visit',
    priority: 'Medium',
    dueAt: iso(1, 10, 0),
    status: 'Pending',
    assignedAgentId: 'agent-priya',
    createdBy: 'agent-priya',
    leadId: 'lead-kabir',
    notes: '4BHK penthouse, family visit.',
    createdAt: iso(-1, 11, 0),
  },
  {
    id: 'task-5',
    title: 'Diwali gift + anniversary card — Ananya Bhatt',
    type: 'Follow-up',
    priority: 'Low',
    dueAt: iso(2, 9, 0),
    status: 'Pending',
    assignedAgentId: 'agent-ananya',
    createdBy: 'agent-ananya',
    leadId: 'lead-ananya-c',
    notes: 'Post-close relationship touchpoint.',
    createdAt: iso(-1, 15, 0),
  },
  {
    id: 'task-6',
    title: 'Confirm Shivalik Parkside handover checklist',
    type: 'Document',
    priority: 'Medium',
    dueAt: iso(-2, 12, 0),
    status: 'Completed',
    assignedAgentId: 'agent-dhruv',
    createdBy: 'admin-kavya',
    propertyId: 'prop-shivalik',
    notes: 'Signed off.',
    createdAt: iso(-5, 10, 0),
    completedAt: iso(-2, 12, 30),
  },
];

const buildThread = (
  contact: string,
  inMessages: [string, number][], // [text, offsetMinutes]
  outMessages: [string, number][] = [],
) => {
  const all = [
    ...inMessages.map(([text, offMin]) => ({
      id: `m-${Math.random().toString(36).slice(2, 8)}`,
      direction: 'in' as const,
      text,
      at: new Date(Date.now() - offMin * 60_000).toISOString(),
    })),
    ...outMessages.map(([text, offMin]) => ({
      id: `m-${Math.random().toString(36).slice(2, 8)}`,
      direction: 'out' as const,
      text,
      at: new Date(Date.now() - offMin * 60_000).toISOString(),
      status: 'read' as const,
    })),
  ].sort((a, b) => new Date(a.at).getTime() - new Date(b.at).getTime());
  return all;
};

export const seedMessages: Message[] = [
  {
    id: 'msg-1',
    channel: 'WhatsApp',
    from: 'Aarav Patel',
    fromContact: '+91 98250 34411',
    preview: 'I liked Shivalik but I am worried about maintenance charges…',
    fullText: 'Hi Dhruv, I like Shivalik Parkside but I am worried about maintenance charges. Can you send me the annual figure? Also, do you have a 3BHK with balcony in a newer building?',
    receivedAt: iso(0, 8, 55),
    isRead: false,
    convertedToLeadId: 'lead-aarav',
    thread: buildThread(
      'Aarav Patel',
      [
        ['Hi Dhruv, I saw the Shivalik Parkside listing.', 260],
        ['I liked the property but I am worried about maintenance charges…', 60],
        ['Can you also share options in newer buildings in Prahlad Nagar?', 55],
      ],
      [
        ['Hi Aarav! Happy to help. Maintenance at Shivalik is ₹4/sqft — annual ~₹95K for 1980 sqft.', 250],
        ['I have 2 newer options: Godrej Garden City and a fresh Shivalik tower. Sending photos.', 245],
      ],
    ),
  },
  {
    id: 'msg-2',
    channel: 'WhatsApp',
    from: 'Ishaan Mehta',
    fromContact: '+91 99745 90712',
    preview: 'Any new launches with flexible payment plan?',
    fullText: 'Any new launches with flexible payment plan? I prefer 20/40/40. Investment horizon 5 years.',
    receivedAt: iso(0, 8, 40),
    isRead: false,
    convertedToLeadId: 'lead-ishaan',
    thread: buildThread(
      'Ishaan Mehta',
      [
        ['Namaste Dhruv, saw your Godrej post.', 130],
        ['Any new launches with flexible payment plan?', 80],
        ['I prefer 20/40/40 structure. Investment horizon 5 years.', 78],
      ],
      [['Namaste Ishaan! Godrej North Star launched last week — 20/40/40, RERA-approved. Sending brochure.', 120]],
    ),
  },
  {
    id: 'msg-3',
    channel: 'Instagram',
    from: 'Diya Desai',
    fromContact: '@diya.desai',
    preview: 'When is the next site visit for Vastrapur?',
    fullText: 'Hi! I saw your Vastrapur listing on IG. When is the next site visit? My budget is around ₹65L.',
    receivedAt: iso(0, 8, 30),
    isRead: false,
    convertedToLeadId: 'lead-diya',
    thread: buildThread('Diya Desai', [
      ['Hi! I saw your Vastrapur listing on IG.', 40],
      ['When is the next site visit?', 38],
      ['My budget is around ₹65L.', 37],
    ]),
  },
  {
    id: 'msg-4',
    channel: 'Facebook',
    from: 'Zeel Trivedi',
    fromContact: 'zeel.trivedi.fb',
    preview: 'Looking for a 3BHK in Satellite — budget ₹1.5 Cr.',
    fullText: 'Hi, looking for a 3BHK in Satellite — budget ₹1.5 Cr. Ready to visit this weekend. Please share options.',
    receivedAt: iso(0, 7, 50),
    isRead: false,
    thread: buildThread('Zeel Trivedi', [
      ['Hi, looking for a 3BHK in Satellite — budget ₹1.5 Cr.', 70],
      ['Ready to visit this weekend.', 68],
      ['Please share options.', 66],
    ]),
  },
  {
    id: 'msg-5',
    channel: 'WhatsApp',
    from: 'Vihaan Trivedi',
    fromContact: '+91 90992 11840',
    preview: 'Please share the registration documents.',
    fullText: 'Please share the registration documents when the seller confirms. Ready to move fast.',
    receivedAt: iso(-1, 16, 15),
    isRead: true,
    convertedToLeadId: 'lead-vihaan',
    thread: buildThread(
      'Vihaan Trivedi',
      [
        ['Please share the registration documents when the seller confirms.', 1200],
        ['Ready to move fast.', 1198],
      ],
      [['Sure Vihaan, chasing the seller now. Will update by EOD.', 1190]],
    ),
  },
  {
    id: 'msg-6',
    channel: 'Instagram',
    from: 'Rakesh Verma',
    fromContact: '@rakesh.verma',
    preview: 'Investor here — new launch in Bopal?',
    fullText: 'Investor here — looking for new launch in Bopal or SG Highway. Budget ₹1.2 Cr. Please DM.',
    receivedAt: iso(-1, 14, 0),
    isRead: false,
    thread: buildThread('Rakesh Verma', [
      ['Investor here — looking for new launch in Bopal or SG Highway.', 1400],
      ['Budget ₹1.2 Cr. Please DM.', 1398],
    ]),
  },
];

export const seedNotifications: AppNotification[] = [
  {
    id: 'notif-1',
    title: 'High-intent lead activity',
    body: 'Aarav Patel viewed Shivalik Parkside twice — score jumped to 87.',
    kind: 'lead',
    createdAt: iso(0, 8, 0),
    read: false,
    leadId: 'lead-aarav',
  },
  {
    id: 'notif-2',
    title: 'Deal risk detected',
    body: 'Aarav Patel — home-loan approval document missing on Shivalik deal.',
    kind: 'risk',
    createdAt: iso(0, 7, 30),
    read: false,
    leadId: 'lead-aarav',
  },
  {
    id: 'notif-3',
    title: 'Task overdue',
    body: 'Chase seller response for Vihaan Trivedi — was due yesterday.',
    kind: 'reminder',
    createdAt: iso(-1, 17, 0),
    read: false,
    taskId: 'task-3',
  },
  {
    id: 'notif-4',
    title: 'New property match',
    body: 'Godrej North Star 2BHK matches Ishaan Mehta at 92%.',
    kind: 'match',
    createdAt: iso(-1, 11, 30),
    read: true,
    leadId: 'lead-ishaan',
  },
];

export const seedNotes: StickyNote[] = [
  {
    id: 'note-1',
    text: 'Site visit Sunday 11am — Aarav + family at Shivalik. Bring floor plan + maintenance sheet.',
    color: 'gold',
    createdAt: iso(0, 7, 0),
    pinned: true,
  },
  {
    id: 'note-2',
    text: 'Kabir prefers Anand Niketan area for schools — filter listings within 2km.',
    color: 'blue',
    createdAt: iso(-1, 15, 0),
  },
];
